### ISSUE TITLE
how and where to add AWS credential to run this aws-s3 source and Sink.

### ISSUE THREAD

**Issue by nucleusbox-ai** [spring-cloud-stream-app-starters/aws-s3#3]
While deploying into Spring cloud dataflow server local I am getting this error.
``` Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-03-05 14:25:58.174 ERROR 32537 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.aws.context.support.io.ResourceLoaderBeanPostProcessor#0': Cannot resolve reference to bean 'amazonS3' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'amazonS3' defined in org.springframework.cloud.stream.app.s3.AmazonS3Configuration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3' threw exception; nested exception is java.lang.IllegalStateException: There is no EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance.

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3' threw exception; nested exception is java.lang.IllegalStateException: There is no EC2 meta data available, because the application is not running in the EC2 environment. Region detection is only possible if the application is running on a EC2 instance

**Comment by artembilan** [comment]
That's info is included into project README: https://github.com/spring-cloud-stream-app-starters/aws-s3/blob/master/spring-cloud-starter-stream-source-s3/README.adoc#amazon-aws-common-options

To avoid that exception you need to specify:
```
cloud.aws.region.auto = false

cloud.aws.region.static = SOME_STATIC_REGION
```
The credential must be supplied via `cloud.aws.credentials.accessKey` and `cloud.aws.credentials.secretKey`.

**Comment by nucleusbox-ai** [comment]
@artembilan I have gone through this document, I have only one question, I know I have to supplie the credential  via `cloud.aws.credentials.accessKey`  and `cloud.aws.credentials.secretKey` but my question is `where` I have to mension this properties, because I am using aws-s3-sink jar directly, and I register this jar in Spring cloud dataflow server local, while deploying the stream I have pass these option propertites, but same exception is throwing. 
so could please lemme know where (in which propertites file) I have to mension this propertites.

**Comment by artembilan** [comment]
Do you have those two options as well:

```
cloud.aws.region.auto = false

cloud.aws.region.static = SOME_STATIC_REGION
```

That is exactly a reason of that error.


All these options should be passed to the `aws-s3-sink` during its deployment into SCDF  as a part of Stream. More info you can get from its docs: https://docs.spring.io/spring-cloud-dataflow/docs/1.3.1.RELEASE/reference/htmlsingle/#_application_properties
